name: Job

on:
  schedule:
    - cron: "0 0-23 * * *"
env:
  CARGO_TERM_COLOR: always
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  API_URI: ${{ secrets.API_URI }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: docker run -e API_URI=$API_URI -e DATABASE_URL=$DATABASE_URL -e ACCESS_TOKEN=$ACCESS_TOKEN ghcr.io/tsugami/send-message-to-kelbi:master
